[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_deps =
    fastled/FastLED @ ^3.6.0
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    bblanchon/ArduinoJson @ ^6.21.3
    esphome/AsyncTCP-esphome @ ^2.0.1
