[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DLED_DATA_PIN=23
    -DNUM_LEDS=88
    -DHAS_HALL_SENSOR=1
    -DHALL_SENSOR_PIN=4
    -DARM_A_PIN=23
    -DARM_B_PIN=18
lib_deps =
    fastled/FastLED @ ^3.7.0
    adafruit/Adafruit LIS3DH @ ^1.2.6
    arduinojson @ ^7.2.0
    me-no-dev/ESP Async WebServer @ ^1.2.3
